entity(f,ball,small,black).
entity(g,table,large,blue).
entity(d,plank,small,green).
entity(e,ball,large,white).
entity(b,brick,small,white).
entity(c,plank,large,red).
entity(a,brick,large,green).
entity(l,box,large,red).
entity(m,box,small,blue).
entity(j,pyramid,small,red).
entity(k,box,large,yellow).
entity(h,table,small,red).
entity(i,pyramid,large,yellow).
